name: Build test RPMs

on:
  push:
    branches: [ "centos7", "el9" ]
  pull_request:
    branches: [ "centos7", "el9" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build using container
      run: make COMMIT=${GITHUB_SHA} docker-build

    - name: Upload built RPMs
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: ffmpeg-nofusion
        # A file, directory or wildcard pattern that describes what to upload
        path: rpmbuild/*/*.rpm
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: warn
        retention-days: 7
