name: Release RPMs

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build using container
      # Feed the version and release according to the Git tag.
      # The tag format should be: 1.2.3-444
      # 1.2.3 is the version, 444 is the release. Extra dashes are considered part of the release.
      run: make COMMIT=${GITHUB_SHA} GIT_TAG=${GITHUB_REF_NAME} VERSION=${GITHUB_REF_NAME%%-*} RELEASE=${GITHUB_REF_NAME#*-} docker-build
      shell: bash

    - name: Calculate checksums
      run: find rpmbuild -maxdepth 1 -type d -exec sh -c 'cd "{}"; sha256sum *.rpm' \; > rpmbuild/SHA256SUMS

    - name: Upload built RPMs
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-nofusion
        path: |
          rpmbuild/*/*.rpm
          rpmbuild/SHA256SUMS
        if-no-files-found: warn
        retention-days: 1

  release:
    runs-on: ubuntu-latest

    needs: [build]

    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ffmpeg-nofusion

    - name: List artifacts
      run: ls -lR

    - name: Create GitHub release
      uses: swisstxt/github-action-release-artifacts@main
      with:
        tag: ${{ github.ref_name }}
        create_release: true
        release_name: "ffmpeg-nofusion ${{ github.ref_name }}"
